[WIP] Add alignment block
M6Web/drinkjs pull request #14
Opened 2016-12-13 16:14 UTC by yohannpoli

2016-12-14 12:21 UTC, oltodo requested changes

2016-12-14 12:21 UTC, oltodo commented on public/index.js
> +    createBlockAlignmentButton({ alignment: 'right', children: <AlignmentRightIcon /> }),
J'appellerais ça plutôt `createTextAlignmentButton`

2016-12-14 12:22 UTC, oltodo commented on src/Draft.css
> +}
CR

2016-12-14 12:30 UTC, oltodo commented on src/plugins/toolbar/utils/getBlockAlignment.js
> +export default getBlockAlignment;
CR

2016-12-14 13:48 UTC, yohannpoli commented on src/plugins/breakout/index.js
> +            data: currentBlockData
on ajoute toutes les data du block courant pour le moment, il faudra peut-être penser à les filter lorsqu'on en aura d'autres

2016-12-15 09:27 UTC, oltodo requested changes

2016-12-15 09:27 UTC, oltodo commented on src/plugins/toolbar/textAlignment.css
> +.alignment--right {
Pas besoin d'utiliser une structure BEM avec CSSModule.

2016-12-15 10:06 UTC, oltodo approved these changes

2016-12-15 10:06 UTC, AntoineReneleau approved these changes

2016-12-15 10:08 UTC, merged