Add link plugin
M6Web/drinkjs pull request #19
Opened 2016-12-21 00:30 UTC by yohannpoli

2016-12-22 07:29 UTC, oltodo commented
Je constate des petits soucis :

![dec -22-2016 08-26-25](https://cloud.githubusercontent.com/assets/483842/21418286/7634e670-c820-11e6-87da-5d24d8e09c18.gif)

Quand tu cliques sur le boutons pour ajouter un lien, la sélection disparait. C'est un peu déroutant. Et le form reste affiché quand tu cliques ailleurs.

2016-12-22 08:46 UTC, oltodo requested changes

2016-12-22 08:46 UTC, oltodo commented on src/plugins/link/icons/NoFollowIcon.js
> +import React, { Component } from 'react';
Fichier à enlever de la PR

2016-12-22 08:46 UTC, oltodo commented on src/plugins/link/icons/TargetBlankIcon.js
> +import React, { Component } from 'react';
Fichier à enlever de la PR

2016-12-22 08:46 UTC, oltodo commented on src/plugins/link/components/Link.css
> +.tooltip {
C'est dommage qu'il y ait des traces de quelque chose qui va arriver dans une autre PR

2016-12-22 08:46 UTC, oltodo commented on src/plugins/link/components/FormLink.js
> +        <input ref={input => this.textInput = input}
Il manque de strictitude le lint.. `ref` devrait passer à la ligne. Je vais regarder pour durcir un peu les règles et voir si le lint est joué au moment des tests.

2016-12-22 08:46 UTC, oltodo commented on src/plugins/link/components/FormLink.js
> +        <input ref={input => this.textInput = input}
Autre remarque, pourquoi utiliser une fonction ? `ref="textInput"` ne suffisait pas ?

2016-12-22 08:46 UTC, oltodo commented on src/plugins/link/components/FormLinkToolbar.css
> +  background-image: linear-gradient(to bottom, rgba(49,49,47,.99), #262625);;
double `;;`

2016-12-22 08:46 UTC, oltodo commented on public/index.js
> +  cancelIcon: <CancelIcon />,
Je ne suis pas sûr de l'intérêt de définir le bouton de fermeture du formulaire. Une croix conviendra dans tous les cas. Je l'enlèverais et le mettrais en dure dans le form perso.

2016-12-22 08:46 UTC, oltodo commented on public/index.js
> +    createLinkButton({ children: <LinkIcon /> }),
Juste une réflexion personnelle.

Je pense qu'à terme on aura peut-être à renommer cette fonction en `createInlineEntityButton`. Cela permettra de gérer à la fois les liens "URL", les liens "objet" sans que ces notions soient ancrées dans DrinkJS.

On aurait par exemple les options :

__Requis :__

- `type` : Type de l'entité (ex: `link`, `object`, `def`, etc)
- `icon` : Le `children` qu'il faudra renommer un jour je pense

__Optionnel :__

- `useTextField` : Le nom est à chier mais en gros c'est pour informer à la toolbar que l'on veut utiliser l'input texte intégré (pour les liens URL donc).
- `useCallback` : Nom à chier également mais ça signifie que les données seront fournies par un callback (pour les liens objets donc)
- `options` : Il s'agit donc de définir les options que l'utilisateur pour par la suite activer par le biais du tooltip (pour le target et le nofollow donc)

Il y a probablement d'autres options qui en découleraient mais en gros, voilà comment je perçois le truc plus tard.

2016-12-22 08:46 UTC, oltodo commented on src/plugins/link/components/FormLink.css
> +  content: '✖';
C'est la croix pour quoi ça du coup ?

2016-12-22 08:46 UTC, oltodo commented on src/plugins/link/components/Link.js
> +    this.forceUpdate();
Il est défini où le `forceUpdate` ?

2016-12-22 08:56 UTC, oltodo requested changes
De manière générale, je trouve assez dommage qu'il y ait dans cette PR des traces choses qui arriveront plus tard

2016-12-22 09:45 UTC, yohannpoli commented on src/plugins/link/components/FormLink.js
> +        <input ref={input => this.textInput = input}
SI ref="value" ça fonctionne bien, c'est juste que je préfère stocker le node directement dans mon instance sans devoir passers par les refs pour le récupérer

2016-12-22 09:47 UTC, yohannpoli commented on src/plugins/link/components/FormLink.css
> +  content: '✖';
et oui, pour le cas ou le cancel icon n'est pas défini justement

2016-12-22 09:47 UTC, yohannpoli commented on public/index.js
> +  cancelIcon: <CancelIcon />,
alors ce paramètre est optionnel

2016-12-22 14:08 UTC, yohannpoli commented on src/plugins/link/components/Link.js
> +    this.forceUpdate();
C'est une méthode de Composant React, du y a accès dès lors que tu extends Component

2016-12-22 14:09 UTC, yohannpoli commented on src/plugins/link/components/Link.js
> +    this.forceUpdate();
Mais du coup se bout de code va sauter de cette PR, ce sera pour les tooltips

2016-12-22 14:24 UTC, oltodo requested changes

2016-12-22 14:24 UTC, oltodo commented on public/state.json
> +        "target": "_self",
Pas nécessaire dans le cadre de cette PR

2016-12-22 14:24 UTC, oltodo commented on src/plugins/link/components/FormLink.js
> +      nofollow: false
Pas nécessaire dans le cadre de cette PR

2016-12-22 14:24 UTC, oltodo commented on src/plugins/link/utils/createLinkEntity.js
> +  return Entity.create(LINK, LINK_MUTABILITY, { url, target, nofollow });
`target` et `nofollow` à retirer

2016-12-22 14:24 UTC, oltodo commented on src/plugins/link/components/Link.js
> +    const { url/*, target, nofollow*/ } = entity.data;
Commentaire à supprimer

2016-12-23 17:00 UTC, yohannpoli commented
J'ai apporté quelques modifications, en prenant en compte ta réflexion, j'ai simplifié et ajouter un createEntityButton.

2017-01-02 06:28 UTC, oltodo commented on src/plugins/link/components/FormLink.css
> +  content: '✖';
Ok, mais selon moi, il n'y a aucune raison de changer l'icône qui sert à fermer la toolbar. La croix est suffisamment pertinente donc autant mettre un SVG en dur. D'autant plus que le rendu sans icône n'est pas super.

![image](https://cloud.githubusercontent.com/assets/483842/21585241/0071d060-d0bd-11e6-9639-9cdbee64b668.png)

2017-01-02 13:51 UTC, oltodo approved these changes

2017-01-02 13:52 UTC, merged